// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yhzcnwdgkiocccnalgfs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InloemNud2Rna2lvY2NjbmFsZ2ZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1MDU5ODcsImV4cCI6MjA3MDA4MTk4N30._6Q6u_OhoYuR4yWwFMGiedvq2f0bz4DIh3Voo7T54HQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});